### ISSUE TITLE
Dark cursor variant

### ISSUE THREAD

**Issue by Vistaus** [yeyushengfan258/Future-cursors#1]
I love the look of this new cursor theme! But how about a dark variant? I would immediately use it if you'd make a dark variant 🙂

Edit: dark as in ‘black’.

**Comment by Vistaus** [comment]
*bump*

**Comment by Meavel** [comment]
https://www.gnome-look.org/p/1457884/

**Comment by Vistaus** [comment]
> https://www.gnome-look.org/p/1457884/

But those are white…

**Comment by Vistaus** [comment]
https://store.kde.org/p/1519633/
Thank you so much for adding them!!! :) :) :)
